* Compound statements (blocks)
- A compound statement is a group of zero or more statements that is treated by the compiler as if it were a single statement.
- Blocks begin with ~{~ and end with a ~}~ symbol.
- Blocks can be used anywhere a single statement is allowed. No semicolon is needed at the end of a block.

* User-defined namespaces and the scope resolution operator
** Defining your own namespaces
#+begin_src 
  namespace NamespaceIdentifier
  {
  // content of namespace here
  }
#+end_src
- It is recommended to use namespace names with capital letters.

** Accessing a namespace with the scope resolution operator (::)
#+begin_src C++
  #include <iostream>

  namespace Foo
  {
    int doSomething(int x, int y)
    {
      return x + y;
    }
  }

  namespace Goo
  {
    int doSomething(int x, int y)
    {
      return x - y;
    }
  }

  int main()
  {
    std::cout << Foo::doSomething(4, 3) << '\n';
    return 0;
  }
#+end_src

#+RESULTS:
: 7

** Using the scope resolution operator with no name prefix
#+begin_src C++
  #include <iostream>

  void print()
  {
    std::cout << " there\n";
  }

  namespace Foo
  {
    void print()
    {
      std::cout << "Hello";
    }
  }

  int main()
  {
    Foo::print(); // call print() in Foo namespace
    ::print(); // call print() in global namespace (same as just calling print() in this case)

    return 0;
  }
#+end_src

#+RESULTS:
: Hello there

** Identifier resolution from within a namespace
- If an identifier is used with no scope resolution, the compiler will first try to find a matching
  declaration in that same namespace. If no matching identifier is found, the compiler will then check each containing namespace in sequence
  to see if a match is found, with the global namespace being checked last.
  #+begin_src C++
    #include <iostream>

    void print() // This print() lives in the global namespace
    {
      std::cout << " there\n";
    }

    namespace Foo
    {
      void print() // this print() lives in the Foo namespace
      {
        std::cout << "Hello";
      }
      void printHelloThere()
      {
        print();   // calls print() in Foo namespace
        ::print(); // calls print() in global namespace
      }
    }
    int main()
    {
      Foo::printHelloThere();

      return 0;
    }
  #+end_src

  #+RESULTS:
  : Hello there
- In the above example, ~print()~ is called with no scope resolution provided. Because we are in ~Foo~ namespace the compiler will find
  Foo::print() before the global ~print()~ and use that.

** Forward declaration of content in namespace
add.h
#+begin_src C++
  #ifndef ADD_H
  #define ADD_H

  namespace BasicMath
  {
    // function add() is part of namespace BasicMath
    int add(int x, int y);
  }

  #endif
#+end_src

add.cpp
#+begin_src C++
  #include "add.h"

  namespace BasicMath
  {
    // define the function add() inside namespace BasicMath
    int add(int x, int y)
    {
      return x + y;
    }
  }
#+end_src

main.cpp
#+begin_src C++
  #include "add.h" // for BasicMath:add()

  #include <iostream>

  int main()
  {
    std::cout << BasicMath::add(4, 3) << '\n';

    return 0;
  }
#+end_src

** Nested namespaces
#+begin_src C++
  #include <iostream>

  namespace Foo
  {
    namespace Goo
    {
      int add(int x, int y)
      {
        return x + y;
      }
    }
  }

  int main()
  {
    std::cout << Foo::Goo::add(1, 2) << '\n';
    return 0;
  }
#+end_src

#+RESULTS:
: 3

C++17 allows you to nest like this:

#+begin_src C++
  #include <iostream>

  namespace Foo::Goo
  {
    int add(int x, int y)
    {
      return x + y;
    }
  }

  int main()
  {
    std::cout << Foo::Goo::add(1, 2) << '\n';
    return 0;
  }
#+end_src

#+RESULTS:
: 3

** Namespace aliases
#+begin_src C++
  #include <iostream>

  namespace Foo::Goo
  {
    int add(int x, int y)
    {
      return x + y;
    }
  }

  int main()
  {
    namespace Active = Foo::Goo; // Active now refers to Foo::Goo
    std::cout << Active::add(1, 2) << '\n';

    return 0;
  }// The alias ends here
#+end_src

#+RESULTS:
: 3

* Local variables
** Local variables have automatic storage duration
- Storage duration determines what rules govern when and how a variable will be created and destroyed.
- Local variables have automatic storage duration, which means they are created at the point of definition
  and destroyed at the end of the block they are defined in.
  #+begin_src C++
    int main()
    {
      int i { 5 }; // i created and intialised here
      double d { 4.0 }; // d created and initalised here

      return 0;
    } // d and i are destroyed here
  #+end_src

** Local variables have no linkage
Identifiers have another property called linkage. An identifiers linkage determines whether a declaration of that same identifier in a different scope
refers to the same object.
- Local variables have no linkage. Each declaration of an identifier with no linkage refers to a unique object or function.
  #+begin_src C++
    int main()
    {
      int x { 2 }; // local variable, no linkage
      {
        int x { 3 }; // this declaration of x refers to a different object than the previous x
      }
      return 0;
    }
  #+end_src
- Linkage determines whether multiple declaration of the same identifier refer
  to the same object or not.
** Variables should be defined in the most limited scope
- Define variables in the most limited existing scope. Avoid creating new blocks whose only purpose is to
  limit the scope of variables.

* Introduction to global variables
** Declaring global variables
- By convention global variables are declared at the top of the file, below the includes, in the global namespace:
  #+begin_src C++
    #include <iostream>

    // Variables declared outside of a function are global variables
    int g_x {}; // global variable g_x

    void doSomething()
    {
      g_x = 3;
      std::cout << g_x << '\n';
    }

    int main()
    {
      doSomething();
      std::cout << g_x << '\n';
      g_x = 5;
      std::cout << g_x << '\n';

      return 0;
    }
  #+end_src

  #+RESULTS:
  | 3 |
  | 3 |
  | 5 |
  
** The scope of global variables
- Global variables can also be defined inside user-defined namespaces:
  #+begin_src C++
    #include <iostream>

    namespace Foo
    {
      int g_x{}; // g_x is now inside the Foo namespace, but it is still a global variable
    }

    void doSomething()
    {
      Foo::g_x = 3;
      std::cout << Foo::g_x << '\n';
    }

    int main()
    {
      doSomething();
      std::cout << Foo::g_x << '\n';

      Foo::g_x = 5;
      std::cout << Foo::g_x << '\n';

      return 0;
    }
  #+end_src

  #+RESULTS:
  | 3 |
  | 3 |
  | 5 |

** Global variables have static duration
- Global variables are created when the program starts, and destroyed when it ends.
- This is called static duration. Variables with static duration are called static variables.

** Naming global variables
"g" or "g_" to indicate they are global
- It helps avoid naming collision with other identifiers in the global namespace.
- It helps prevent inadvertent name shadowing.
- It helps indicate that the prefixed variables persist beyond the scope of the function, and thus
  any changes we make to it will persist.

** Constant global variables
#+begin_src C++
  #include <iostream>

  const int g_y { 1 }; // const global variable g_y, initialised with a value
  constexpr int g_z { 2 }; // constexpr global variable g_z, initialised with a value

  void doSomething()
  {
    std::cout << g_y << '\n';
    std::cout << g_z << '\n';
  }

  int main()
  {
    doSomething();
    std::cout << g_y << '\n';
    std::cout << g_z << '\n';
    
    return 0;
  }
#+end_src

#+RESULTS:
| 1 |
| 2 |
| 1 |
| 2 |

* Variable shadowing (name hiding)
- Avoid variable shadowing.

* Internal linkage
- An identifier's linkage determines whether other declarations of that name refer
  to the same object or not.
- Global variables and function identifiers can have either ~internal linkage~ or ~external linkage~.
- An identifier with internal linkage can be seen and used within a single translation unit, but it
  is not accessible from other translation units.
- This means that if two source files have identically named identifiers with internal linkage
  those identifiers will be treated as independent.
  
** Global variables with internal linkage
- Global variables with internal linkage are sometimes called internal variables.
  To make a non-constant global variable internal, we use the ~static~ keyword.

  #+begin_src C++ 
    #include <iostream>

    static int g_x{}; // non-constant globals have external by default but can be given internal linkage via static keyword

    const int g_y{ 1 }; // const globals have internal linkage by default
    constexpr int g_z{ 2 }; // constexpr globals have internal linkage by default

    int main()
    {
      std::cout << g_x << ' ' << g_y << ' ' << g_z << '\n';

      return 0;
    }
  #+end_src

  #+RESULTS:
  : 0 1 2

a.cpp
#+begin_src C++ 
  [[maybe_unused]] constexpr int g_x { 2 }; // only accessible within a.cpp
#+end_src

#+RESULTS:

main.cpp
#+begin_src C++
  #include <iostream>

  static int g_x { 3 }; // this separate internal g_x is only accessible within main.cpp

  int main()
  {
    std::cout << g_x << '\n'; // uses main.cpp's g_x prints 3

    return 0;
  }
#+end_src

#+RESULTS:
: 3

** Function with internal linkage
add.cpp
#+begin_src C++ :tangle ~/cplusplusrepo/practiceH/learncpp/solutions/chapter_7_examples/add.cpp 
  // This function is defined as static, and now can only be used within this file
  // Attempts to access it from another file via a function forward declaration will fail

  [[maybe_unused]] static int add(int x, int y)
  {
    return x + y;
  }
#+end_src
main.cpp
#+begin_src C++ :tangle ~/cplusplusrepo/practiceH/learncpp/solutions/chapter_7_examples/main.cpp
  #include <iostream>

  int add(int x, int y); // forward decleration for function add

  int main()
  {
    std::cout << add(3, 4) << '\n';

    return 0;
  }
#+end_src

- Many modern development guides recommend giving every variable and function that isn't meant to be used
from another file internal linkage.

** Quick Summary
#+begin_src C++
  static int g_x;      // defines non-initialised internal global variable
  static int g_x{ 1 }; // defines initialised internal global variable

  const int g_y { 2 }; // defines initialised internal global const variable
  constexpr int g_y { 3 }; // defines initialised internal global constexpr variable


  // internal function definitions
  static int foo() {}; // define internal function
#+end_src

* External linkage and variable forward declarations
- An identifier with external linkage can be seen and used from the file in which it is defined, and from other
  code files (via a forward declaration). They are truly "global" in that they can be used anywhere in the program.

** Functions have external linkage by default
- In order to call a function defined in another file, you must place a forward declaration for the function in any other files
  wishing to use the function.
- The forward declaration tells the compiler of the existence of the function, and the linker connects the function calls to the actual function definition.

  #+begin_src C++
    #include <iostream>

    void sayHi() // function has external linkage, and can be seen by other files
    {
      std::cout << "Hi!\n";
    }
  #+end_src

  #+begin_src C++
    void sayHi(); // forward declaration for function sayHi, makes sayHi accessible in this file.

    int main()
    {
      sayHi(); // call the function defined in another file, linker will connect this call to the function definition

      return 0;
    }
  #+end_src

** Global variables with external linkage
- Global variables with external linkage are sometimes called external variables.
  #+begin_src C++
    int g_x { 2 }; // non constant globals are external by default (no need to use extern)

    extern const int g_y { 3 }; // const globals can be defined as extern, making them external

    extern constexpr int g_z { 3 }; // constexpr globals can be defined as extern, making them external (this is pretty much useless)

    int main()
    {

      return 0;
    }
  #+end_src
- non-constant global variables are external by default,
  so we don't need to mark them as ~extern~.

** Variable forward declaration via the extern keyword
main.cpp
#+begin_src C++
  #include <iostream>

  extern int g_x; // this extern is a forward declaration of a variable named g_x that is defined somewhere else
  extern const int g_y; // this extern is a forward declaration of a const variable named g_y that is defined somewhere else.

  int main()
  {
    std::cout << g_x << ' ' << g_y << '\n';

    return 0;
  }
#+end_src

#+begin_src C++
  int g_x { 2 }; // non constant globals have external linkage by default
  extern const int g_y { 3 }; // this extern gives g_y external linkage
#+end_src

- If you to define an uninitialised non const global variable, do not use the extern keyword, otherwise C++ will
  think that you are trying to make a forward declaration.
- constexpr can be given external linkages using ~extern~ keyword, they can not be forward declared as contexpr. As the compiler needs to know the value at compile time.
  If that value is in another file then the compiler has no visibility on what that value is defined as.

- Function forward declarations don't need an ~extern~ keyword as the compiler is able to tell whether you're defining a new function or making a forward declaration based on whether you are
  providing the function body or not.

- Variable forward declarations need an ~extern~ keyword to help differentiate uninitialised variables definitions from variable forward declarations.

  #+begin_src C++
    // non-constant
    int g_x;        // variable definition (no intialiser)
    int g_x { 1 };  // variable definition (w/ initialiser)
    extern int g_x; // forward declaration (no initialiser)

    // constant
    extern const int g_y { 1 }; // variable definition (const requires initialisers)
    extern const int g_y;       // forward declaration (no intialiser)
  #+end_src

** Avoid using ~extern~ on a non-const global variable with an intialiser
#+begin_src C++
  int g_x { 1 };        // extern by default
  extern int g_x { 1 }; // explicitly extern (may cause compiler warning)
#+end_src

- Only use ~extern~ for global variable forward declaration or const global variable definitions
- Do not use ~extern~ for non-const global variables definitions (that are implicitly ~extern~)

** Quick summary
#+begin_src C++
  // Global variable forward declaration (extern w/ no initialiser):
  extern int g_y;          // forward declaration for non-constant global variable
  extern const int g_y;    // forward declaration for const global variable
  extern constexpr int g_y;// not allowed: constexpr variables cannot be forward declared

  // External global variable definitions (no extern)
  int g_x;                  // defines non-initialised external global variable (zero initialised by default)
  int g_x { 1 };            // defines initialised external global variable

  // External const global variable definitions (extern w/ initialiser)
  extern const int g_x { 2 };     // defines initialised const external global variable
  extern constexpr int g_x { 3 }; // defines initialised constexpr external global variable
#+end_src

* Why (non-const) global variables are evil
- Global variables make the program's state unpredictable.
- Every function call becomes potentially dangerous.
- Global variables make your code less modular and less flexible. Modularity helps in both understanding of the program,
  as well as reusability. Global variables reduce reusability significantly.

** The initialisation order problem of global variables
Initialisation of static variables (which includes global variables) happens as part of program startup, before execution of the ~main~ function.
This proceeds in two phases:
- The first phase is called static initialisation, Static initialisation occurs in two steps:
  - Global variables with constexpr initialisers (including literals) are initialised to those values. This is called constant initialisation.
  - Global variables without initialisers are zero-initialised. zero-initialisation is considered to be a form of static initialisation since ~0~ is a contexpr value.
- The second phase is dynamic initialisation. This phase is more complex and nuanced, but the gist is that global variables with non-constexpr initalisers are initialised.
Example of a non-constexpr initialiser:
#+begin_src C++
  int init()
  {
    return 5;
  }

  int g_something{ init() }; // non-constexpr initialisation
#+end_src

- Global variables should only ever be one of the thing the variable represents in your program, and its use should be ubiquitous throughout your program.

* Inline functions and variables
- For every function call there is a overhead on the CPU.
- Normally for bigger functions the function call overhead is typically negligible compared to the cost of the function.
- However, for small functions that are used frequently this adds up.
** Inline Expansion
- The C++ compiler does Inline Expansion where the function call is replaced with the body of the function.
Example:
#+begin_src C++
  #include <iostream>

  int min(int x, int y)
  {
    return (x < y) ? x : y;
  }

  int main()
  {
    std::cout << min(5,6) << '\n';
    std::cout << min(3,2) << '\n';

    return 0;
  }
#+end_src
#+begin_src C++
  #include <iostream>

  int main()
  {
    std::cout << ((5 < 6) ? 5 : 6) << '\n';
    std::cout << ((3 < 2) ? 3 : 2) << '\n';
    return 0;
  }
#+end_src

#+RESULTS:
| 5 |
| 2 |
- The min() function is replaced with the body of the min() function.

** The performance of inline code
- Inline expansion is best suited to short, simple functions, especially when the function will be called more than once.
  e.g. function calls inside a loop

** When inline expansion occurs
- May be expanded (most functions are in this category)
- Can't be expanded

** The inline keyword, historically
- The ~inline~ keyword was used to hint the compiler to expand a function inline.
- Do not use the ~inline~ keyword to request inline expansion on your functions as the compiler is better at doing it.

** Inline keyword, modernly
- Modernly it means "multiple definitions allowed"
Example:
main.cpp
#+begin_src C++
  #include <iostream>

  double circumference(double radius); // forward declaration

  inline double pi() { return 3.14159; }

  int main()
  {
    std::cout << pi() << '\n';
    std::cout << circumference(2.0) << '\n';

    return 0;
  }
#+end_src

math.cpp
#+begin_src C++
  inline double pi() { return 3.14159; }

  double circumference(double radius)
  {
    return 2.0 * pi() * radius;
  }
#+end_src

- Inline functions are typically defined in header files

pi.h
#+begin_src C++ :main no :tangle pi.h
  #infndef PI_H
  #define PI_H

  inline double pi() { return 3.14159; }

  #endif
#+end_src

main.cpp
#+begin_src C++ :tangle main.cpp
  #include "pi.h" // include a copy of pi() here
  #include <iostream>

  double circumference(double radius); // forward declaration

  int main()
  {
    std::cout << pi() << '\n';
    std::cout << circumference(2.0) << '\n';
    
    return 0;
  }
#+end_src

math.cpp
#+begin_src C++ :main no :tangle math.cpp
  #include "pi.h"

  double circumference(double radius)
  {
    return 2.0 * pi() * radius;
  }
#+end_src

- Avoid the use of the ~inline~ keyword unless you have a specific, compelling reason to do so.

* Sharing global constants across multiple files (using inline variables)
** Global constants as internal variables
1) Create a header file to hold these constants
2) Inside this header file, define a namespace
3) Add all your constants inside the namespace
4) \#include the header file whenever you need it

constants.h
   #+begin_src C++
     #ifndef CONSTANTS_H
     #define CONSTANTS_H

     namespace constants
     {
       constexpr double pi { 3.14159 };
       constexpr double avogadro { 6.022e23 };
       constexpr double myGravity { 9.2 };
     }

     #endif
   #+end_src
main.cpp
#+begin_src C++
  #include "constants.h"

  #include <iostream>

  int main()
  {
    std::cout << "Enter a radius: ";
    double radius{};
    std::cin >> radius;

    std::cout << "The circumference is " << 2 * radius * constants::pi << '\n';

    return 0;
  }
#+end_src

Advantages
- Works prior to C++17
- Can be used in constant expressions in any translation unit that includes them

Disadvantages
- Changing anything in the header file recompiled files including the header
- Each translation unit including the header gets its own copy of the variable

** Global constants as external variables
constants.cpp
#+begin_src C++
  #include "constants.h"

  namespace constants
  {
    extern constexpr double pi { 3.14159 };
    extern constexpr double avogadro { 6.022e23 };
    extern constexpr double myGravity { 9.2 }; // lighter
  }
#+end_src

constants.h
#+begin_src C++
  #ifndef CONSTANTS_H
  #define CONSTANTS_H

  namespace constants
  {
    extern const double pi;
    extern const double avogadro;
    extern const double myGravity;
  }

  #endif
#+end_src

main.cpp
#+begin_src C++
  #include "constants.h" // include all the forward declarations

  #include <iostream>

  int main()
  {
    std::cout << "Enter a radius: ";
    double radius{};
    std::cin >> radius;

    std::cout << "The circumference is: " << 2 * radius * constants::pi << '\n';

    return 0;
  }
#+end_src

Advantages:
- Works prior to C++17
- Only one copy of each variable is required
- Only requires recompilation of one file if the value of the constant changes
Disadvantages:
- Forward declaration and variable definitions are in separate files, and must be kept in sync
- Variables not usable in constant expressions outside of the file in which they are defined

** Global constants as inline variables C++17
constants.h
#+begin_src C++
  #ifndef CONSTANTS_H
  #define CONSTANTS_H

  namespace constants
  {
    inline constexpr double pi { 3.14159 };
    inline constexpr double avogadro { 6.022e23 };
    inline constexpr double myGravity { 9.2 };
  }
  #endif
#+end_src

main.cpp
#+begin_src C++
  #include "constants.h"

  #include <iostream>

  int main()
  {
    std::cout << "Enter a radius: ";
    double radius{};
    std::cin >> radius;

    std::cout << "The circumference is: " << 2 * radius * constants::pi << '\n';

    return 0;
  }
#+end_src

Advantages:
- Can be used in constant expressions in any translation unit that includes them
- Only one copy of each variable is required

Downsides:
- Only works in C++17 onwards.
- Changing anythin in header file requires recompiling files including the header.


Best practice:
- If you need global constants and your compiler is C++17 capable, prefer defining
  inline constexpr global variables in a header file
- Use std::string_view for constexpr strings.

* Static local variables
- Local Variables have automatic duration, means they are created at the point of definition and destroyed when the block is exited.
- =static= keyword changes its duration from automatic duration to static duration.
- This means they are now created at the *start* of the program, and destroyed at the end of the program (just like a global variable).
- As a result static variables will retain its value even after it goes out of scope.

Automatic duration example:

#+begin_src C++
  #include <iostream>

  void incrementAndPrint()
  {
    int value { 1 }; // automatic duration by default
    ++value;
    std::cout << value << '\n';
  } // value destroyed here
  
  int main()
  {
    incrementAndPrint();
    incrementAndPrint();
    incrementAndPrint();
    
    return 0;
  }
#+end_src

#+RESULTS:
| 2 |
| 2 |
| 2 |

Static duration example:
#+begin_src C++
  #include <iostream>

  void incrementAndPrint()
  {
    static int s_value{ 1 };
    ++s_value;
    std::cout << s_value << '\n';
  }

  int main()
  {
    incrementAndPrint();
    incrementAndPrint();
    incrementAndPrint();

    return 0;
  }
#+end_src

#+RESULTS:
| 2 |
| 3 |
| 4 |

- Static local variables that are zero-initialised or have a constexpr initialiser can be
  initialised at program start.
- Static local variables that have no initialiser or a non-constexpr initialiser are zero-initialised at program start.
  Static local variables with a non-constexpr value are reinitialised the first time variable definition is encountered.
- The definition is skipped on subsequent calls, so no further reinitialisation occurs.
- Static local variables have static duration that are no explicitly initialised are zero-initialised by default.

- Always initialise local static variables. Static variables are only initialised the first time the code is executed,
  not on subsequent calls.

** ID generation
One of the most common uses for static duration local variables is for unique ID generators.

#+begin_src C++
  #include <iostream>

  int generateID()
  {
    static int s_itemID{ 0 };
    return s_itemID++; // makes copy of s_itemID, increments the real s_itemID, then returns the value in the copy
  }

  int main()
  {
    const int id_1 { generateID() };
    const int id_2 { generateID() };
    
    std::cout << id_1 << ' ' << id_2 << '\n';
    
    return 0;
  }
#+end_src

#+RESULTS:
: 0 1

** Don't use static local variables to alter flow
- Const static local variable are generally okay to use
- Avoid using non-const static local variables. If you do use them ensure the
  variable needs to be reset, and isn't used to alter program flow.

- When applied to a global variable static keyword defines the global variable has internal linkage
  meaning the variable cannot be exported to other files.
- When applied to a local variable, the keyword static defines the local variable as having static duration, meaning
  the variable will only be created once, and will not be destroyed until the end of the program.

* Scope, duration, and linkage summary
Duration:
- Automatic duration:
  - Local variables
  - Function parameters
  - Program defined definitions such as enums and classes declared inside a block
- Static Duration:
  - Global variables
  - Static local variables
- Dynamic duration are created and destroyed at the programmers request
  - Dynamically allocated variables 

linkage
- No linkage (unique entity)
  - Local variable
  - Programmed defined type identifiers (such as enums and classes) declared inside a block
- Internal linkage (in the same source file they refere to the same object or function)
  - Static global variables (initialised or uninitialised)
  - Static functions
  - Const global variables
  - Unnamed namespaces and anything defined within them
- External linkage
  - Non-static functions
  - Non-const global variables (initialised or uninitialised)
  - Extern const global variables
  - Inline const global variables
  - Namespaces

* Unnamed and inline namespaces
- Benefits of unnamed namespace is that whatever is inside it will have internal linkage.
- inline namespaces don't affect linkage.
