- favour constexpr if statements over non-constexpr if statements when the conditional is a constant expression.

Switch statement:
#+begin_src C++
  #include <iostream>

  void printDigitalName(int x)
  {
    switch (x)
      {
      case 1:
        std::cout << "one";
        return;
      case 2:
        std::cout << "two";
        return;
      case 3:
        std::cout << "three";
        return;
      default:
        std::cout << "Unknown";
        return;
      }
  }

  int main()
  {
    printDigitalName(2);
    std::cout << '\n';

    return 0;
  }
#+end_src

#+RESULTS:
: two

- If we don't have a return or a break in our switch statement then we get a fallthrough,
  where it goes through all the cases below it.
  
- If you are intentionally doing a fallthrough use ~[[fallthrough]]~ there.
  
- If you place case labels in sequence you can bunch up a few cases together before returning them.
  
- No implicit blocks are created by the labels, they are all scoped within the switch block.

- You can explicitly make blocks in the cases like:
  #+begin_src C++
    switch(1)
      {
      case 1:
        {
          int x { 4 }; // okay inside a block
          std::cout << x;
          break;
        }
      default:
        std::cout << "default case\n";
        break;
      }
  #+end_src

  #+begin_src C++
    #include <iostream>

    void printUpto(int outer)
    {
      int inner { 1 };
      while (inner <= outer)
        {
          std::cout << inner << ' ';
          ++inner;
        }
    }

    int main()
    {
      int outer{ 1 };
      while (outer <= 5)
        {
          printUpto(outer);
          std::cout << '\n';
          ++outer;
        }
      return 0;
    }
  #+end_src

  #+RESULTS:
  | 1 |   |   |   |   |
  | 1 | 2 |   |   |   |
  | 1 | 2 | 3 |   |   |
  | 1 | 2 | 3 | 4 |   |
  | 1 | 2 | 3 | 4 | 5 |

  #+begin_src C++
    #include <iostream>

    int main()
    {
      char ascii = { 'a' };
      while( ascii < '{' )
        {
          std::cout << ascii << ' ' << static_cast<int>(ascii) << '\n';
          ++ascii;
        }
      
      return 0;
    }
  #+end_src

  #+RESULTS:
  | a |  97 |
  | b |  98 |
  | c |  99 |
  | d | 100 |
  | e | 101 |
  | f | 102 |
  | g | 103 |
  | h | 104 |
  | i | 105 |
  | j | 106 |
  | k | 107 |
  | l | 108 |
  | m | 109 |
  | n | 110 |
  | o | 111 |
  | p | 112 |
  | q | 113 |
  | r | 114 |
  | s | 115 |
  | t | 116 |
  | u | 117 |
  | v | 118 |
  | w | 119 |
  | x | 120 |
  | y | 121 |
  | z | 122 |

  #+begin_src C++
    #include <iostream>

    int main()
    {
      int outerloop { 5 };
      while(outerloop > 0){
        int innerloop {outerloop};
        while(innerloop > 0){
          std::cout << innerloop << ' ';
          --innerloop;
        }
        std::cout << '\n';
        --outerloop;
      }
      
      return 0;
    }
  #+end_src

  #+RESULTS:
  | 5 | 4 | 3 | 2 | 1 |
  | 4 | 3 | 2 | 1 |   |
  | 3 | 2 | 1 |   |   |
  | 2 | 1 |   |   |   |
  | 1 |   |   |   |   |

- for loops you should avoid setting the condition to be operator!=
- You can have multiple variables and counters in a for loop you need to separate them with the ,operator.
- Fizz Buzz

  #+begin_src C++
    #include <iostream>

    void fizzbuzz(int max)
    {
      for(int i {1}; i <= max; i++){
        if( i % 3 == 0 && i % 5 == 0 ){
          std::cout << "fizzbuzz";
        } else if( i % 3 == 0 ){
          std::cout << "fizz" << '\n';
        } else if( i % 5 == 0 ){
          std::cout << "buzz" << '\n';
        } else{
          std::cout << i << '\n';
        }
      }
    }

    int main()
    {
      fizzbuzz(15);
      
      return 0;
    }
  #+end_src

  #+RESULTS:
  |        1 |
  |        2 |
  |     fizz |
  |        4 |
  |     buzz |
  |     fizz |
  |        7 |
  |        8 |
  |     fizz |
  |     buzz |
  |       11 |
  |     fizz |
  |       13 |
  |       14 |
  | fizzbuzz |

- Break is used in a switch to prevent fallthrough to subsequent cases.
- In a loop break is used to terminate the loop early
- A break will break out of a switch or a loop, a return will exit out of the functin that the loop is within.

